on:
  push:
    branches: [ main ]

name: update
jobs:
  run:
    name: Create PR with updated articles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: davnn/fastpaced
          token: ${{ secrets.FASTPACED_FGPAT }}

      - name: Update submodule
        run: git submodule update --init --remote

      - name: Create a PR in target repo
        env:
          GITHUB_TOKEN: ${{ secrets.FASTPACED_FGPAT }}
        run: |
          TARGET_REPO="davnn/fastpaced"
          BRANCH_NAME="update-articles"
          PR_TITLE=":memo: Update articles"
          PR_BODY="This PR was created automatically."

          # Set up git identity
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          # Create a new branch for the PR
          git checkout -b $BRANCH_NAME

          # Make any changes here if necessary
          git commit -am ":memo: Update articles"

          # Push the changes to the remote
          git push origin $BRANCH_NAME -f

          # Create a pull request
          gh pr create \
            --base "main" \
            --head "$BRANCH_NAME" \
            --repo "$TARGET_REPO" \
            --title "$PR_TITLE" \
            --body "$PR_BODY"
