on:
  push:
    branches: [ main ]

name: update
jobs:
  run:
    name: Create PR with updated articles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: davnn/fastpaced

      - name: Update submodule
        run: git submodule update --init --remote

      - name: Create a PR in target repo
        run: |
          TARGET_REPO="davnn/fastpaced"
          BRANCH_NAME="update-articles"
          PR_TITLE=":memo: Update articles"
          PR_BODY="This PR was created automatically."

          # Set up git identity
          git config --global user.email "muhrdavid+github@gmail.com"
          git config --global user.name "David Muhr"

          # Create a new branch for the PR
          git checkout -b $BRANCH_NAME
          # Make any changes here if necessary
          git commit -am ":memo: Update articles"
          git push origin $BRANCH_NAME

          # Create a pull request
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$TARGET_REPO/pulls \
            -d '{
              "title": "'"$PR_TITLE"'",
              "head": "'"$BRANCH_NAME"'",
              "base": "main",  # Base branch in the target repo
              "body": "'"$PR_BODY"'"
            }'
